# In this section of the config you can change all the messages in the plugin.
# For messages please use the minimessage formatting, see https://docs.adventure.kyori.net/minimessage/format.html#minimessage-format
must-be-player: "<red>You must be a player to use this command!</red>" # Message shown when a player tries to use a command that requires them to be a player
no-permission: "<red>You do not have permission to use this command!</red>" # Message shown when a player tries to use a command that they don't have permission to use
player-not-found: "<red>Player not found!</red>" # Message shown when a player does not exist
toggle-staffmode-on: "<green>Toggled staffmode on!</green>" # Message shown when a player toggles staffmode on
toggle-staffmode-off: "<red>Toggled staffmode off!</red>" # Message shown when a player toggles staffmode off
toggle-vanish-on: "<green>Toggled vanish on!</green>" # Message shown when a player toggles vanish on
toggle-vanish-off: "<red>Toggled vanish off!</red>" # Message shown when a player toggles vanish off
toggle-freeze-on: "<red>You have been frozen! Do not log out.</red>" # Message shown when a player gets frozen.
toggle-freeze-off: "<green>You have been unfrozen!</green>" # Message shown when a player gets unfrozen.
currently-frozen: "<red>You are currently frozen! Do not log out.</red>" # Message shown when a player tries to use a move while they are frozen.

# In this section of the config you can change the items given to you in staffmode. Please do not use colors here.
staffmode-hotbar: # List of items to give the player when they toggle staffmode, available items: "DISABLE_STAFFMODE", "FREEZE_WAND", "INVENTORY_WAND", "KB_STICK", "VANISH_ITEM"
  1: "DISABLE_STAFFMODE"
  2: ""
  3: "FREEZE_WAND"
  4: ""
  5: "INVENTORY_WAND"
  6: ""
  7: "KB_STICK"
  8: ""
  9: "VANISH_ITEM"
# For items, please use `&` color codes.
items:
  DISABLE_STAFFMODE:
    item: "LIME_DYE"
    name: "&cDisable Staffmode"
  FREEZE_WAND:
    item: "CHAIN"
    name: "&bFreeze Wand"
  INVENTORY_WAND:
    item: "BLAZE_ROD"
    name: "&cInventory Wand"
  KB_STICK:
    item: "STICK"
    name: "&cKnockback Stick"
  VANISH_ITEM:
    item: "BARRIER"
    name: "&rVanish"