name: Staff
version: '${project.version}'
main: me.fivevl.staff.Main
api-version: 1.18
authors: [ 5vl ]
description: A staffing plugin.
depend:
  - PlaceholderAPI
commands:
  staffmode:
    description: The command to go into staffmode.
  vanish:
    description: Vanish from all players!
    aliases:
      - v
  invsee:
    description: View someones inventory.